-- moviestream.000010.view_customer.sql
CREATE OR REPLACE EDITIONING VIEW customer AS
   SELECT
      CUST_ID , LAST_NAME , FIRST_NAME , EMAIL , STREET_ADDRESS ,
      POSTAL_CODE , CITY , STATE_PROVINCE , COUNTRY_CODE ,
      YRS_CUSTOMER , PROMOTION_RESPONSE , LOC_LAT , LOC_LONG ,
      AGE , COMMUTE_DISTANCE , CREDIT_BALANCE , EDUCATION ,
      FULL_TIME , GENDER , HOUSEHOLD_SIZE , INCOME ,
      INCOME_LEVEL , INSUFF_FUNDS_INCIDENTS , JOB_TYPE ,
      LATE_MORT_RENT_PMTS , MARITAL_STATUS , MORTGAGE_AMT ,
      NUM_CARS , NUM_MORTGAGES , PET , RENT_OWN , SEGMENT_ID ,
      WORK_EXPERIENCE , YRS_CURRENT_EMPLOYER , YRS_RESIDENCE
     FROM
      CUSTOMER$0;
