-- Bllewell

SET SQLPROMPT "  !  "
SET BLOCKTERMINATOR ON
SET SQLBLANKLINES ON
SET SQLTERMINATOR OFF
SET DEFINE OFF

SET TRIMSPOOL ON
SET ECHO OFF
SET FEEDBACK OFF
SET VERIFY OFF
SET PAGESIZE 50000
SET LINESIZE 32727
SET SERVEROUTPUT ON FORMAT WRAPPED SIZE UNLIMITED

COLUMN EDITION_NAME FORMAT A30
COLUMN PARENT_EDITION_NAME FORMAT A30
COLUMN USABLE FORMAT A6

-- Used for the SHOW ERRORS command
COLUMN LINE/COL FORMAT A8
COLUMN ERROR    FORMAT A65  WORD_WRAPPED

COLUMN PK     FORMAT 999
COLUMN c      FORMAT A30
COLUMN c_wide FORMAT A30
